import { API_ENDPOINTS } from "config/api";
import { STORIES_SHOWED_TYPE } from "constants/storiesTypes";

export const storiesTypeConfig = {
  [STORIES_SHOWED_TYPE.ASK]: API_ENDPOINTS.ASK_STORIES,
  [STORIES_SHOWED_TYPE.BEST]: API_ENDPOINTS.BEST_STORIES,
  [STORIES_SHOWED_TYPE.JOB]: API_ENDPOINTS.JOB_STORIES,
  [STORIES_SHOWED_TYPE.NEW]: API_ENDPOINTS.NEW_STORIES,
  [STORIES_SHOWED_TYPE.SHOW]: API_ENDPOINTS.SHOW_STORIES,
  [STORIES_SHOWED_TYPE.TOP]: API_ENDPOINTS.TOP_STORIES,
};
